package com.myweb.dao;

public class Columns {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columns.id
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columns.table
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    private String table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columns.column
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    private String column;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column columns.chinese
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    private String chinese;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columns.id
     *
     * @return the value of columns.id
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columns.id
     *
     * @param id the value for columns.id
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columns.table
     *
     * @return the value of columns.table
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columns.table
     *
     * @param table the value for columns.table
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public void setTable(String table) {
        this.table = table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columns.column
     *
     * @return the value of columns.column
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public String getColumn() {
        return column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columns.column
     *
     * @param column the value for columns.column
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public void setColumn(String column) {
        this.column = column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column columns.chinese
     *
     * @return the value of columns.chinese
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column columns.chinese
     *
     * @param chinese the value for columns.chinese
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    public void setChinese(String chinese) {
        this.chinese = chinese;
    }
}