package com.myweb.pojo;

public class Role2menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role2menu.id
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role2menu.role
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role2menu.menuid
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role2menu.id
     *
     * @return the value of role2menu.id
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role2menu.id
     *
     * @param id the value for role2menu.id
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role2menu.role
     *
     * @return the value of role2menu.role
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role2menu.role
     *
     * @param role the value for role2menu.role
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role2menu.menuid
     *
     * @return the value of role2menu.menuid
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role2menu.menuid
     *
     * @param menuid the value for role2menu.menuid
     *
     * @mbg.generated Mon Dec 19 15:09:14 CST 2016
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}