package com.myweb.pojo;

import java.math.BigDecimal;

public class Caiji {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.laorenid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer laorenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.laorenname
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String laorenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.gaoya
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer gaoya;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.diya
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer diya;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.xuetang
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private BigDecimal xuetang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.maibo
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer maibo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.xueyang
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer xueyang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.tizhong
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private BigDecimal tizhong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.shengao
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer shengao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.bmi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private BigDecimal bmi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.huxi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer huxi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.time
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String createusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caiji.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.id
     *
     * @return the value of caiji.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.id
     *
     * @param id the value for caiji.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.laorenid
     *
     * @return the value of caiji.laorenid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getLaorenid() {
        return laorenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.laorenid
     *
     * @param laorenid the value for caiji.laorenid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setLaorenid(Integer laorenid) {
        this.laorenid = laorenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.laorenname
     *
     * @return the value of caiji.laorenname
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getLaorenname() {
        return laorenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.laorenname
     *
     * @param laorenname the value for caiji.laorenname
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setLaorenname(String laorenname) {
        this.laorenname = laorenname == null ? null : laorenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.gaoya
     *
     * @return the value of caiji.gaoya
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getGaoya() {
        return gaoya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.gaoya
     *
     * @param gaoya the value for caiji.gaoya
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setGaoya(Integer gaoya) {
        this.gaoya = gaoya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.diya
     *
     * @return the value of caiji.diya
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getDiya() {
        return diya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.diya
     *
     * @param diya the value for caiji.diya
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setDiya(Integer diya) {
        this.diya = diya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.xuetang
     *
     * @return the value of caiji.xuetang
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public BigDecimal getXuetang() {
        return xuetang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.xuetang
     *
     * @param xuetang the value for caiji.xuetang
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setXuetang(BigDecimal xuetang) {
        this.xuetang = xuetang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.maibo
     *
     * @return the value of caiji.maibo
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getMaibo() {
        return maibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.maibo
     *
     * @param maibo the value for caiji.maibo
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setMaibo(Integer maibo) {
        this.maibo = maibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.xueyang
     *
     * @return the value of caiji.xueyang
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getXueyang() {
        return xueyang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.xueyang
     *
     * @param xueyang the value for caiji.xueyang
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setXueyang(Integer xueyang) {
        this.xueyang = xueyang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.tizhong
     *
     * @return the value of caiji.tizhong
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public BigDecimal getTizhong() {
        return tizhong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.tizhong
     *
     * @param tizhong the value for caiji.tizhong
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setTizhong(BigDecimal tizhong) {
        this.tizhong = tizhong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.shengao
     *
     * @return the value of caiji.shengao
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getShengao() {
        return shengao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.shengao
     *
     * @param shengao the value for caiji.shengao
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setShengao(Integer shengao) {
        this.shengao = shengao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.bmi
     *
     * @return the value of caiji.bmi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public BigDecimal getBmi() {
        return bmi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.bmi
     *
     * @param bmi the value for caiji.bmi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setBmi(BigDecimal bmi) {
        this.bmi = bmi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.huxi
     *
     * @return the value of caiji.huxi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getHuxi() {
        return huxi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.huxi
     *
     * @param huxi the value for caiji.huxi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setHuxi(Integer huxi) {
        this.huxi = huxi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.time
     *
     * @return the value of caiji.time
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.time
     *
     * @param time the value for caiji.time
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.createuser
     *
     * @return the value of caiji.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.createuser
     *
     * @param createuser the value for caiji.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.createusername
     *
     * @return the value of caiji.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getCreateusername() {
        return createusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.createusername
     *
     * @param createusername the value for caiji.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreateusername(String createusername) {
        this.createusername = createusername == null ? null : createusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caiji.createtime
     *
     * @return the value of caiji.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caiji.createtime
     *
     * @param createtime the value for caiji.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }
}