package com.myweb.pojo;

public class Fuwu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.laorenid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer laorenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.laorenname
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String laorenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.xiangmu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String xiangmu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.shuoming
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String shuoming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.time
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.fuwutype
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String fuwutype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String createusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fuwu.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.id
     *
     * @return the value of fuwu.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.id
     *
     * @param id the value for fuwu.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.laorenid
     *
     * @return the value of fuwu.laorenid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getLaorenid() {
        return laorenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.laorenid
     *
     * @param laorenid the value for fuwu.laorenid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setLaorenid(Integer laorenid) {
        this.laorenid = laorenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.laorenname
     *
     * @return the value of fuwu.laorenname
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getLaorenname() {
        return laorenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.laorenname
     *
     * @param laorenname the value for fuwu.laorenname
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setLaorenname(String laorenname) {
        this.laorenname = laorenname == null ? null : laorenname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.xiangmu
     *
     * @return the value of fuwu.xiangmu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getXiangmu() {
        return xiangmu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.xiangmu
     *
     * @param xiangmu the value for fuwu.xiangmu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setXiangmu(String xiangmu) {
        this.xiangmu = xiangmu == null ? null : xiangmu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.shuoming
     *
     * @return the value of fuwu.shuoming
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getShuoming() {
        return shuoming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.shuoming
     *
     * @param shuoming the value for fuwu.shuoming
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setShuoming(String shuoming) {
        this.shuoming = shuoming == null ? null : shuoming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.time
     *
     * @return the value of fuwu.time
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.time
     *
     * @param time the value for fuwu.time
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.fuwutype
     *
     * @return the value of fuwu.fuwutype
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getFuwutype() {
        return fuwutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.fuwutype
     *
     * @param fuwutype the value for fuwu.fuwutype
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setFuwutype(String fuwutype) {
        this.fuwutype = fuwutype == null ? null : fuwutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.createuser
     *
     * @return the value of fuwu.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.createuser
     *
     * @param createuser the value for fuwu.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.createusername
     *
     * @return the value of fuwu.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getCreateusername() {
        return createusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.createusername
     *
     * @param createusername the value for fuwu.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreateusername(String createusername) {
        this.createusername = createusername == null ? null : createusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fuwu.createtime
     *
     * @return the value of fuwu.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fuwu.createtime
     *
     * @param createtime the value for fuwu.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }
}