package com.myweb.pojo;

public class Laoren {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.name
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.sex
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.age
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.nation
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.birthday
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.idnumber
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String idnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.address
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.phone
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.mobile
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String createusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.type
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laoren.bingshi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String bingshi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.id
     *
     * @return the value of laoren.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.id
     *
     * @param id the value for laoren.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.name
     *
     * @return the value of laoren.name
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.name
     *
     * @param name the value for laoren.name
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.sex
     *
     * @return the value of laoren.sex
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.sex
     *
     * @param sex the value for laoren.sex
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.age
     *
     * @return the value of laoren.age
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.age
     *
     * @param age the value for laoren.age
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.nation
     *
     * @return the value of laoren.nation
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.nation
     *
     * @param nation the value for laoren.nation
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.birthday
     *
     * @return the value of laoren.birthday
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.birthday
     *
     * @param birthday the value for laoren.birthday
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.idnumber
     *
     * @return the value of laoren.idnumber
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.idnumber
     *
     * @param idnumber the value for laoren.idnumber
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.address
     *
     * @return the value of laoren.address
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.address
     *
     * @param address the value for laoren.address
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.phone
     *
     * @return the value of laoren.phone
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.phone
     *
     * @param phone the value for laoren.phone
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.mobile
     *
     * @return the value of laoren.mobile
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.mobile
     *
     * @param mobile the value for laoren.mobile
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.createuser
     *
     * @return the value of laoren.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.createuser
     *
     * @param createuser the value for laoren.createuser
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.createtime
     *
     * @return the value of laoren.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.createtime
     *
     * @param createtime the value for laoren.createtime
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.createusername
     *
     * @return the value of laoren.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getCreateusername() {
        return createusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.createusername
     *
     * @param createusername the value for laoren.createusername
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setCreateusername(String createusername) {
        this.createusername = createusername == null ? null : createusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.type
     *
     * @return the value of laoren.type
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.type
     *
     * @param type the value for laoren.type
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laoren.bingshi
     *
     * @return the value of laoren.bingshi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getBingshi() {
        return bingshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laoren.bingshi
     *
     * @param bingshi the value for laoren.bingshi
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setBingshi(String bingshi) {
        this.bingshi = bingshi == null ? null : bingshi.trim();
    }
}