package com.myweb.pojo;

public class Roletomenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletomenu.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletomenu.role
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roletomenu.menuid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletomenu.id
     *
     * @return the value of roletomenu.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletomenu.id
     *
     * @param id the value for roletomenu.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletomenu.role
     *
     * @return the value of roletomenu.role
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletomenu.role
     *
     * @param role the value for roletomenu.role
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roletomenu.menuid
     *
     * @return the value of roletomenu.menuid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roletomenu.menuid
     *
     * @param menuid the value for roletomenu.menuid
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}