package com.myweb.pojo;

public class Shuxing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.chinese
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.name
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.chinesename
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String chinesename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.remark
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.shunxu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    private Integer shunxu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.id
     *
     * @return the value of shuxing.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.id
     *
     * @param id the value for shuxing.id
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.chinese
     *
     * @return the value of shuxing.chinese
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.chinese
     *
     * @param chinese the value for shuxing.chinese
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.name
     *
     * @return the value of shuxing.name
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.name
     *
     * @param name the value for shuxing.name
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.chinesename
     *
     * @return the value of shuxing.chinesename
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getChinesename() {
        return chinesename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.chinesename
     *
     * @param chinesename the value for shuxing.chinesename
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setChinesename(String chinesename) {
        this.chinesename = chinesename == null ? null : chinesename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.remark
     *
     * @return the value of shuxing.remark
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.remark
     *
     * @param remark the value for shuxing.remark
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.shunxu
     *
     * @return the value of shuxing.shunxu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public Integer getShunxu() {
        return shunxu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.shunxu
     *
     * @param shunxu the value for shuxing.shunxu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    public void setShunxu(Integer shunxu) {
        this.shunxu = shunxu;
    }
}