package com.myweb.dao.mybatis.mapper;

import com.myweb.pojo.Fuwu;
import com.myweb.pojo.FuwuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FuwuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    long countByExample(FuwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int deleteByExample(FuwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int insert(Fuwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int insertSelective(Fuwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    List<Fuwu> selectByExample(FuwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    Fuwu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") Fuwu record, @Param("example") FuwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByExample(@Param("record") Fuwu record, @Param("example") FuwuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByPrimaryKeySelective(Fuwu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fuwu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByPrimaryKey(Fuwu record);
}