package com.myweb.dao.mybatis.mapper;

import com.myweb.pojo.Roletomenu;
import com.myweb.pojo.RoletomenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoletomenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    long countByExample(RoletomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int deleteByExample(RoletomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int insert(Roletomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int insertSelective(Roletomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    List<Roletomenu> selectByExample(RoletomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    Roletomenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") Roletomenu record, @Param("example") RoletomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByExample(@Param("record") Roletomenu record, @Param("example") RoletomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByPrimaryKeySelective(Roletomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletomenu
     *
     * @mbg.generated Fri Dec 23 22:04:23 CST 2016
     */
    int updateByPrimaryKey(Roletomenu record);
}