package com.myweb.mybatis;

import com.myweb.pojo.mybatis.Tableinfo;
import com.myweb.pojo.mybatis.TableinfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TableinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int countByExample(TableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int deleteByExample(TableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int insert(Tableinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int insertSelective(Tableinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    List<Tableinfo> selectByExample(TableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    Tableinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tableinfo record, @Param("example") TableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tableinfo record, @Param("example") TableinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tableinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tableinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tableinfo record);
}