package com.myweb.vo.mybatis;

public class Renyuan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.name
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.sex
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.age
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.nation
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.birthday
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.idnumber
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String idnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.address
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.phone
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.mobile
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.createuser
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column renyuan.cretetime
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private String cretetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.id
     *
     * @return the value of renyuan.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.id
     *
     * @param id the value for renyuan.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.name
     *
     * @return the value of renyuan.name
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.name
     *
     * @param name the value for renyuan.name
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.sex
     *
     * @return the value of renyuan.sex
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.sex
     *
     * @param sex the value for renyuan.sex
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.age
     *
     * @return the value of renyuan.age
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.age
     *
     * @param age the value for renyuan.age
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.nation
     *
     * @return the value of renyuan.nation
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.nation
     *
     * @param nation the value for renyuan.nation
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.birthday
     *
     * @return the value of renyuan.birthday
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.birthday
     *
     * @param birthday the value for renyuan.birthday
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.idnumber
     *
     * @return the value of renyuan.idnumber
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.idnumber
     *
     * @param idnumber the value for renyuan.idnumber
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.address
     *
     * @return the value of renyuan.address
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.address
     *
     * @param address the value for renyuan.address
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.phone
     *
     * @return the value of renyuan.phone
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.phone
     *
     * @param phone the value for renyuan.phone
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.mobile
     *
     * @return the value of renyuan.mobile
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.mobile
     *
     * @param mobile the value for renyuan.mobile
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.createuser
     *
     * @return the value of renyuan.createuser
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.createuser
     *
     * @param createuser the value for renyuan.createuser
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column renyuan.cretetime
     *
     * @return the value of renyuan.cretetime
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public String getCretetime() {
        return cretetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column renyuan.cretetime
     *
     * @param cretetime the value for renyuan.cretetime
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setCretetime(String cretetime) {
        this.cretetime = cretetime;
    }
}