package com.myweb.vo.mybatis;

public class Ry2sx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry2sx.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry2sx.renyuanId
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer renyuanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry2sx.bingshiId
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer bingshiid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry2sx.id
     *
     * @return the value of ry2sx.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry2sx.id
     *
     * @param id the value for ry2sx.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry2sx.renyuanId
     *
     * @return the value of ry2sx.renyuanId
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getRenyuanid() {
        return renyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry2sx.renyuanId
     *
     * @param renyuanid the value for ry2sx.renyuanId
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setRenyuanid(Integer renyuanid) {
        this.renyuanid = renyuanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry2sx.bingshiId
     *
     * @return the value of ry2sx.bingshiId
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getBingshiid() {
        return bingshiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry2sx.bingshiId
     *
     * @param bingshiid the value for ry2sx.bingshiId
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setBingshiid(Integer bingshiid) {
        this.bingshiid = bingshiid;
    }
}