package com.myweb.vo.mybatis;

public class Ry2sx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry2sx.id
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry2sx.laorenid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    private Integer laorenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ry2sx.bingshiid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    private Integer bingshiid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry2sx.id
     *
     * @return the value of ry2sx.id
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry2sx.id
     *
     * @param id the value for ry2sx.id
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry2sx.laorenid
     *
     * @return the value of ry2sx.laorenid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public Integer getLaorenid() {
        return laorenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry2sx.laorenid
     *
     * @param laorenid the value for ry2sx.laorenid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public void setLaorenid(Integer laorenid) {
        this.laorenid = laorenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ry2sx.bingshiid
     *
     * @return the value of ry2sx.bingshiid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public Integer getBingshiid() {
        return bingshiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ry2sx.bingshiid
     *
     * @param bingshiid the value for ry2sx.bingshiid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public void setBingshiid(Integer bingshiid) {
        this.bingshiid = bingshiid;
    }
}