package com.myweb.vo.mybatis;

public class Shuxing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.id
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.type
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.name
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.id
     *
     * @return the value of shuxing.id
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.id
     *
     * @param id the value for shuxing.id
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.type
     *
     * @return the value of shuxing.type
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.type
     *
     * @param type the value for shuxing.type
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.name
     *
     * @return the value of shuxing.name
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.name
     *
     * @param name the value for shuxing.name
     *
     * @mbggenerated Tue May 03 21:51:50 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}