package com.myweb.vo.mybatis;

public class Tableinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.id
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.table_name
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.column_name
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.chinese
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    private String chinese;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.id
     *
     * @return the value of tableinfo.id
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.id
     *
     * @param id the value for tableinfo.id
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.table_name
     *
     * @return the value of tableinfo.table_name
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.table_name
     *
     * @param tableName the value for tableinfo.table_name
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.column_name
     *
     * @return the value of tableinfo.column_name
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.column_name
     *
     * @param columnName the value for tableinfo.column_name
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.chinese
     *
     * @return the value of tableinfo.chinese
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.chinese
     *
     * @param chinese the value for tableinfo.chinese
     *
     * @mbggenerated Wed Apr 27 11:59:10 CST 2016
     */
    public void setChinese(String chinese) {
        this.chinese = chinese;
    }
}