package com.myweb.vo.mybatis;

public class User2menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.menu_id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.user_id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.id
     *
     * @return the value of user2menu.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.id
     *
     * @param id the value for user2menu.id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.menu_id
     *
     * @return the value of user2menu.menu_id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.menu_id
     *
     * @param menuId the value for user2menu.menu_id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.user_id
     *
     * @return the value of user2menu.user_id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.user_id
     *
     * @param userId the value for user2menu.user_id
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}