package com.myweb.vo.mybatis;

public class User2menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.id
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.menuid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.userid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.id
     *
     * @return the value of user2menu.id
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.id
     *
     * @param id the value for user2menu.id
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.menuid
     *
     * @return the value of user2menu.menuid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.menuid
     *
     * @param menuid the value for user2menu.menuid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.userid
     *
     * @return the value of user2menu.userid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.userid
     *
     * @param userid the value for user2menu.userid
     *
     * @mbggenerated Tue May 03 01:16:45 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}