package com.myweb.pojo.mybatis;

public class Shuxing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.id
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.type
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.chinesetype
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    private String chinesetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.name
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.remark
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shuxing.shunxu
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    private Integer shunxu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.id
     *
     * @return the value of shuxing.id
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.id
     *
     * @param id the value for shuxing.id
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.type
     *
     * @return the value of shuxing.type
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.type
     *
     * @param type the value for shuxing.type
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.chinesetype
     *
     * @return the value of shuxing.chinesetype
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public String getChinesetype() {
        return chinesetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.chinesetype
     *
     * @param chinesetype the value for shuxing.chinesetype
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public void setChinesetype(String chinesetype) {
        this.chinesetype = chinesetype == null ? null : chinesetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.name
     *
     * @return the value of shuxing.name
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.name
     *
     * @param name the value for shuxing.name
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.remark
     *
     * @return the value of shuxing.remark
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.remark
     *
     * @param remark the value for shuxing.remark
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shuxing.shunxu
     *
     * @return the value of shuxing.shunxu
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public Integer getShunxu() {
        return shunxu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shuxing.shunxu
     *
     * @param shunxu the value for shuxing.shunxu
     *
     * @mbg.generated Fri Dec 02 21:10:04 CST 2016
     */
    public void setShunxu(Integer shunxu) {
        this.shunxu = shunxu;
    }
}