package com.myweb.pojo.mybatis;

public class Tableinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.id
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.tablename
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private String tablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.columnname
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private String columnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.chinese
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private String chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.tabledisable
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private String tabledisable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.modaldisable
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private String modaldisable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.type
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.shunxu
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    private Integer shunxu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.id
     *
     * @return the value of tableinfo.id
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.id
     *
     * @param id the value for tableinfo.id
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.tablename
     *
     * @return the value of tableinfo.tablename
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.tablename
     *
     * @param tablename the value for tableinfo.tablename
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.columnname
     *
     * @return the value of tableinfo.columnname
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.columnname
     *
     * @param columnname the value for tableinfo.columnname
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setColumnname(String columnname) {
        this.columnname = columnname == null ? null : columnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.chinese
     *
     * @return the value of tableinfo.chinese
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.chinese
     *
     * @param chinese the value for tableinfo.chinese
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.tabledisable
     *
     * @return the value of tableinfo.tabledisable
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public String getTabledisable() {
        return tabledisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.tabledisable
     *
     * @param tabledisable the value for tableinfo.tabledisable
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setTabledisable(String tabledisable) {
        this.tabledisable = tabledisable == null ? null : tabledisable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.modaldisable
     *
     * @return the value of tableinfo.modaldisable
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public String getModaldisable() {
        return modaldisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.modaldisable
     *
     * @param modaldisable the value for tableinfo.modaldisable
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setModaldisable(String modaldisable) {
        this.modaldisable = modaldisable == null ? null : modaldisable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.type
     *
     * @return the value of tableinfo.type
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.type
     *
     * @param type the value for tableinfo.type
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.shunxu
     *
     * @return the value of tableinfo.shunxu
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public Integer getShunxu() {
        return shunxu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.shunxu
     *
     * @param shunxu the value for tableinfo.shunxu
     *
     * @mbg.generated Wed Oct 26 10:38:11 CST 2016
     */
    public void setShunxu(Integer shunxu) {
        this.shunxu = shunxu;
    }
}