package com.myweb.pojo.mybatis;

public class User2menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.id
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.shuxingid
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    private Integer shuxingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2menu.menuid
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.id
     *
     * @return the value of user2menu.id
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.id
     *
     * @param id the value for user2menu.id
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.shuxingid
     *
     * @return the value of user2menu.shuxingid
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    public Integer getShuxingid() {
        return shuxingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.shuxingid
     *
     * @param shuxingid the value for user2menu.shuxingid
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    public void setShuxingid(Integer shuxingid) {
        this.shuxingid = shuxingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2menu.menuid
     *
     * @return the value of user2menu.menuid
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2menu.menuid
     *
     * @param menuid the value for user2menu.menuid
     *
     * @mbggenerated Sat May 07 23:06:45 CST 2016
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}