package com.myweb.dao;

import com.myweb.dao.Shuxing;
import com.myweb.dao.ShuxingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShuxingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int countByExample(ShuxingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int deleteByExample(ShuxingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int insert(Shuxing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int insertSelective(Shuxing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    List<Shuxing> selectByExample(ShuxingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    Shuxing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") Shuxing record, @Param("example") ShuxingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int updateByExample(@Param("record") Shuxing record, @Param("example") ShuxingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int updateByPrimaryKeySelective(Shuxing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shuxing
     *
     * @mbggenerated Thu Apr 07 21:58:03 CST 2016
     */
    int updateByPrimaryKey(Shuxing record);
}