package com.myweb.dao.mybatis;

import com.myweb.pojo.mybatis.Usertomenu;
import com.myweb.pojo.mybatis.UsertomenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsertomenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int countByExample(UsertomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int deleteByExample(UsertomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int insert(Usertomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int insertSelective(Usertomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    List<Usertomenu> selectByExample(UsertomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    Usertomenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Usertomenu record, @Param("example") UsertomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Usertomenu record, @Param("example") UsertomenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Usertomenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertomenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Usertomenu record);
}