package com.myweb.vo.mybatis;

public class Tableinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.id
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.tablename
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.columnname
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    private String columnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.chinese
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.type
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tableinfo.shunxu
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    private Integer shunxu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.id
     *
     * @return the value of tableinfo.id
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.id
     *
     * @param id the value for tableinfo.id
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.tablename
     *
     * @return the value of tableinfo.tablename
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.tablename
     *
     * @param tablename the value for tableinfo.tablename
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.columnname
     *
     * @return the value of tableinfo.columnname
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.columnname
     *
     * @param columnname the value for tableinfo.columnname
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.chinese
     *
     * @return the value of tableinfo.chinese
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.chinese
     *
     * @param chinese the value for tableinfo.chinese
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public void setChinese(String chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.type
     *
     * @return the value of tableinfo.type
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.type
     *
     * @param type the value for tableinfo.type
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tableinfo.shunxu
     *
     * @return the value of tableinfo.shunxu
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public Integer getShunxu() {
        return shunxu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tableinfo.shunxu
     *
     * @param shunxu the value for tableinfo.shunxu
     *
     * @mbggenerated Sat May 07 18:53:18 CST 2016
     */
    public void setShunxu(Integer shunxu) {
        this.shunxu = shunxu;
    }
}