package com.myweb.dao.mybatis;

import com.myweb.vo.mybatis.Columns;
import com.myweb.vo.mybatis.ColumnsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int countByExample(ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int deleteByExample(ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int insert(Columns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int insertSelective(Columns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    List<Columns> selectByExample(ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    Columns selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") Columns record, @Param("example") ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int updateByExample(@Param("record") Columns record, @Param("example") ColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int updateByPrimaryKeySelective(Columns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table columns
     *
     * @mbggenerated Tue Apr 26 14:19:20 CST 2016
     */
    int updateByPrimaryKey(Columns record);
}