package com.myweb.dao.mybatis;

import com.myweb.vo.mybatis.User2menu;
import com.myweb.vo.mybatis.User2menuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User2menuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int countByExample(User2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int deleteByExample(User2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int insert(User2menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int insertSelective(User2menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    List<User2menu> selectByExample(User2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    User2menu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") User2menu record, @Param("example") User2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int updateByExample(@Param("record") User2menu record, @Param("example") User2menuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int updateByPrimaryKeySelective(User2menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2menu
     *
     * @mbggenerated Tue Apr 26 22:43:12 CST 2016
     */
    int updateByPrimaryKey(User2menu record);
}